# Generated by Django 4.2.1 on 2023-05-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(default='COMPANY_name', max_length=180),
        ),
    ]
