# Generated by Django 4.2.1 on 2023-05-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_transaction_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(default='COMPANY_NAME', max_length=180),
        ),
    ]
